---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  word_document:
    toc: no
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Caroline Cummings, cac7659

#### Introduction 

When the Agricultural Revolution began in the 1940s, it initiated a global switch from small-scale subsistence farming to large-scale industrialized agriculture. As a result, humans have increasingly deforested and encroached upon natural lanscapes. Agricultural expansion is a leading driver of deforestation, and livestock production is particularly destructive because it requires a significant amount of land both to provide livestock space to live and to grow feed stock. In fact, cattle is a leading cause of deforestation in the Amazon, and a majority of soy production in this region is used to feed cattle instead of humans. Agricultural expansion and intensification has also had negative implications on infectious disease emergence and spread. Land-use change is a major driver of the emergence of new infectious diseases, and it can exacerbate the prevalence of endemic pathogens. Malaria cases are shown to increase when deforestation occurs due to a phenomenon called the "edge effect." When forests are fragmented (due to land-use change such as deforestation and agriculture), the wildlife-livestock-human interface can become disrupted and lead to ecosystem imbalances. Wildlife, livestock, and humans come in contact with each other more frequently and interact in abnormal ways due to increased surface area between natural and human-changed land. In areas where there is a significant forest edge, malaria incidence is shown to increase because a) an increased number of people become available food sources for mosquitoes, b) animals that usually serve as food sources to mosquitoes die or become displaced due to habitat loss, and c) forest edges provide suitable habitat for mosquitoes. 

I chose to analyze 4 datasets that contained the 1) malaria cases per 100,000 people, 2) percent of land used for agriculture, 3) percent of land that is covered by forest, and the 4) Livestock Production Index for countries between the years 1995-2005 to see if there is a notable relationship between these variables. Each dataset included one of the variables listed above, the corresponding countries, and the year. The csv files for the datasets were downloaded from GapMinder. I expect for malaria cases, agricultural land, and livestock production to increase over time and for the forest cover to decrease. Understanding the relationship between these variables is especially important now as medical resources have shifted away from  prevention and treatment programs for endemic dieases, such as malaria, due to the reallocation of resources to combat COVID-19. 

```{R}
# read your datasets in here, e.g., with read_csv()
library(tidyverse)
library(dplyr)

agriculture<-read_csv("agriculture.csv")
livestock <- read_csv("livestock.csv")
forest_coverage <- read_csv("forest_coverage.csv")
malaria_prop <- read_csv("malaria_prop.csv")
```

#### Tidying: Reshaping

For all 4 datasets, I used pivot_longer to create a column for the year variable for the years between 1995-2005. I used select to only pull data on my ID variable, the years 1995-2005, and the malaria/land/agriculture/livestock data. My ID variable is "country," so to prevent the "year" column from duplicating when I joined the 4 datasets, I united the country and year columns. Also, I used an underscore to combine these data because if I used a space, it would be difficult to separate these data back into "country" and "year" because some countries are more than one word (ex: Papua New Guinea).

```{R}
#Demonstration that I can use pivot wider/longer:
tidy_forest<- forest_coverage %>% pivot_longer(c("1995":"2005"), names_to="year", values_to="forest_cover") %>% select(country, year, forest_cover)
tidy_forest %>% pivot_wider(names_from="year", values_from="forest_cover")

#Data actually used:
#Forest: The percent of a country's total land area that is covered in forest each year
forest_coverage1 <- forest_coverage %>% pivot_longer(c("1995":"2005"), names_to="year", values_to="forest_cover") %>% select(country, year, forest_cover)
new_forest<- forest_coverage1 %>% unite(country, year, col="country_year", sep="_")

#Malaria: malaria cases per 100,000 people each year
malaira_prop1 <- malaria_prop %>% pivot_longer(c("1995":"2005"), names_to="year", values_to="malaria") %>% select(country, year, malaria)
new_malaria_prop <-malaira_prop1 %>% unite(country, year, col="country_year", sep="_")

#Agriculture: the percent of a country's total land area that is permanently used for crops or pasture
agriculture1 <- agriculture %>% pivot_longer(c("1995":"2005"), names_to="year", values_to="agriculture") %>% select(country, year, agriculture)
new_agriculture <-agriculture1 %>% unite(country, year, col="country_year", sep="_")

#Livestock: An index that provides a measure of livestock production outputs (meat, milk, etc.) for a country each year
livestock1 <- livestock %>% pivot_longer(c("1995":"2005"), names_to="year", values_to="livestock") %>% select(country, year, livestock)
new_livestock <- livestock1 %>% unite(country, year, col="country_year", sep="_")

```

    
#### Joining/Merging

```{R}
# your joining code
first_join<- inner_join(new_forest, new_malaria_prop, by="country_year")
second_join<- inner_join(new_agriculture, new_livestock, by="country_year")
final_join <- inner_join(first_join, second_join, by="country_year")

#separate country and year
final_join<- final_join %>% separate("country_year", into=c("country", "year"), sep="_")

#total rows in each dataset
nrow(forest_coverage)
nrow(malaria_prop)
nrow(agriculture)
nrow(livestock)

#unique IDs in each dataset
n_distinct(forest_coverage)
n_distinct(malaria_prop)
n_distinct(agriculture)
n_distinct(livestock)

#IDs that appear in one dataset but not the other
anti<- forest_coverage %>% anti_join(malaria_prop, by="country")
anti %>% summarize(n_distinct(country))
head(anti)

#IDs that the datasets have in common
final_join %>% summarize(n_distinct(country))

#Additional code for discussion
malaria_prop %>% anti_join(final_join, by="country")
n_distinct(forest_coverage)- final_join %>% summarize(n_distinct(country))

```
Process:
I joined all 4 datasets together using inner_join. I chose to use inner_join because it allowed me to keep only the data that had a match for each country (the ID variable) for each year between 1995 and 2005. Thus, if the livestock data did not include an entry for Angola, then Angola would not be included in the final dataset. After I joined all the data together via inner_join, I used separate to split the "country_year" variable into "country" and "year." In the end, I had six variables in total (country, year, percent of land that is covered in forest compared to total land area (forest_cover), percent of land that is used for agriculture compared to total land area (agriculture), Livestock Production Index (livestock), and malaria cases per 100,000 people (malaria)).

Calculations Discussion: There are 230 rows in the forest dataset, 107 rows in the malaria dataset, 211 rows in the agriculture dataset, and 202 rows in the livestock dataset. The number of distinct IDs is the same as the number of rows for each dataset because there are no duplicate data points of the countries. There are 123 IDs in the forest dataset that are missing in the malaria dataset, which indicates that 123 countries are not included in the malaria dataset but are present in the forest data. This includes Aruba and the Netherlands Antilles. As demonstrated by the final inner_join between the 4 datasets ("final_join"), the datasets have 106 ID variables in common. In other words, there are 106 countries that appear in all 4 datasets. 124 observations were dropped from the forest dataset, 1 from malaria, 105 from agriculture, and 96 from livestock. The size of the final joined data is about half of the size of original datasets, except for the malaria data. Only one country, French Guiana, appeared in the malaria dataset but not the final joined dataset. Losing data points could have a negative impact on the analyses of these data because the results are less likely to be representative of the real world. Additionally, having a large sample size is important to reduce the margin of error and to decrease how much outliers can skew the data. Therefore, I have an increased risk of having results that are inaccurate and less representative of trends that are actually happening in the real world.


####  Wrangling

```{R}
# wrangling code
#convert variables to numeric
final_join$year <-as.numeric(as.character(final_join$year))
final_join$malaria <- as.numeric(sub("k", "e3", final_join$malaria, fixed= TRUE))

#reorganize data
final_join<- final_join %>% select(country, year, forest_cover, agriculture, everything())

```

```{R}
#Summary Statistics Demonstration
library(knitr)
library(kableExtra)

#1: Average number of malaria cases (per 100,000 people) for each country from 1995-2005
final_join %>% group_by(country) %>% na.omit() %>% summarize(mean_malaria=mean(malaria)) %>% arrange(desc(mean_malaria)) %>% head() %>% kable(align = 'l', digits = 3) %>% kable_styling(font_size = 15)

final_join %>% group_by(country) %>% na.omit() %>% summarize(mean_malaria=mean(malaria)) %>% filter(country=="China")

#2: Categorical variable table of counts
final_join %>% group_by(country) %>% na.omit %>% summarize(n=n())

#3: Missing values for each variable- Define a function (user-defined) and use it inside summarize
final_join %>% summarize_all(function(x) sum(is.na(x)))

#4: Overall Summary Statistics for Livestock Production Index and Forest Cover using different functions
final_join %>% group_by(country) %>% na.omit() %>% summarize(sd_livestock=sd(livestock), sd_forest=sd(forest_cover), mean_livestock=mean(livestock), mean_forest=mean(forest_cover), n=n(), se_livestock=sd_livestock/sqrt(n), se_forest=sd_forest/sqrt(n)) %>% select(country, n, mean_livestock, mean_forest, everything()) %>% arrange(desc(mean_livestock)) %>% head() %>% kable(align = 'lccccccc', digits = 3) %>% kable_styling(font_size = 10) 

#5: Summary Statistics for Countries that overlap with the Amazon Rainforest
final_join %>% filter(country %in% c("Brazil","Columbia", "Peru", "Bolivia", "Venezuela", "Guyana", "Suriname")) %>% group_by(country) %>% na.omit() %>% summarize(mean_malaria=mean(malaria), mean_livestock=mean(livestock), mean_agriculture=mean(agriculture), mean_forest=mean(forest_cover)) %>% select(country, mean_malaria, mean_forest, mean_agriculture, mean_livestock) %>% arrange(mean_malaria) %>% kable(align = 'lcccc', digits = 3) %>% kable_styling(font_size = 15)

```
For #1, I grouped the data by country and used summarize to find the average number of malaria cases (per 100,000 people) from 1995-2005. I then arranged the resulting data from highest malaria incidence rate to lowest and found that Zambia had the highest overall rate of malaria incidence (35,800 cases/100,000 people). I was also curious to see what China's overall malaria incidence rate was because China is undergoing significant agricultural expansion and intensification, and the rate of malaria incidence was much lower than Zambia's (6.04 cases/100,000 people). For #2, I found the counts of the categorical variable (country) for each level, and it was 11 for most countries. This is logical because I used data from countries for each year between 1995 and 2005 (11 years total, and some countries might be missing data for a few years). For #3, I created a function inside of summarize to report the number of missing values for each variable (with "sum"). For #4, I found summary statistics using functions such as mean, sd, etc. for forest cover and the Livestock Production Index for each country averaged over the 11 years. The data are arranged from highest to lowest livestock production because I was curious to see if there appeared to be a relationship between livestock production and forest cover. For #5, I filtered the data to only include Amazonian countries, calculated the averages of the variables for each country using group_by, summarize, and the mean, and arranged the data from lowest to highest malaria incidence rate. Select was used to only show mean values of the variables with their corresponding countries. It appears that Amazonian countries that have less forest cover have a lower average rate of malaria incidence (between 1995-2005).


```{R}
#5: Continued Summary Statistics Demonstration- Nigeria's Statistics
library(gt)

Nigeria_table<- final_join %>% filter(country=="Nigeria") %>% mutate("malaria/forest_cover"=malaria/forest_cover) %>% select(-agriculture, -livestock)

Nigeria_table %>% gt %>% tab_header(title=md("**Nigeria**"), subtitle=md("A table of malaria cases per 100,000 people and the percent of land covered in forest")) %>% tab_spanner(label="Variables", columns=c("country", "year","malaria", "forest_cover", "malaria/forest_cover"))

#6: stringr demonstration
final_join %>% distinct(country) %>% summarize("n_countries_>1_word"=sum(str_detect(country, "[ ]")))
final_join %>% distinct(country) %>% slice_max(str_length(country))

#7: Comparisons of means and medians for malaria cases, forest cover, agricultural land, and livestock production. Continued tidying demonstration.
final_join %>% na.omit %>% summarize(mean_malaria=mean(malaria), median_malaria=median(malaria), mean_forest=mean(forest_cover), median_forest=median(forest_cover), mean_agriculture=mean(agriculture), median_agriculture=median(agriculture), mean_livestock=mean(livestock), median_livestock=median(livestock)) %>% pivot_longer(1:8, names_to="variable",values_to="value") %>% separate(variable,into=c("number","variable")) %>% 
  pivot_wider(names_from="number",values_from="value") %>% kable(align = 'lcc', digits = 3) %>% kable_styling(font_size = 15)


```
For #5, I filtered the data to only show data for Nigeria, which is a country known for having one of the highest rates of deforestation. I used mutate to create a new variable comparing the rate of malaria incidence as a function of the percent of land covered by forest, and I used gt to create a table to depict the data for each year. It appears that as the percent of land covered in forest decreases, the rate of malaria cases increases over time. For #6, I used str_detect to find countries that include a space in their name (i.e. are longer than 1 word). I used distinct to remove any duplicate and summarize with sum to find the total number of different countries that are longer than 1 word. There are 20. I also used slice max to provide the country with the longest character length (calculated using str_length), and it was "Central African Republic." For #7, I used summarize to find the means and medians of the variables malaria cases per 100,000 people, percent of land covered in forest, percent of land used for agriculture, and the Livestock Production Index. When the mean and median are close, this indicates the data are likely normally distributed. When the mean and median differ, this indicates the data are probably skewed. The mean and median for each of variables were similar for all the variables except for malaria. The mean malaria cases (per 100,000 people) was 5,087.15, and the median was 525, which indicates the data is probably positively skewed. For the table, I used pivot_longer to make columns for the variables and their corresponding numerical values. I used separate to separate the each "variable" from its type of "number" (mean/median). Lastly, pivot_wider was used to create columns for the means and medians from "number".

#### Visualizing

```{R}
# Plot #1
library(ggplot2)

ggplot(data = final_join, aes(x = agriculture, y = forest_cover)) + geom_point(aes(color=year, size=malaria))+
  geom_smooth(method="lm")+ scale_color_gradient(low="green", high="red")+ ggtitle("Land Used for Agriculture vs Covered in Forest in Different Countries Over Time")+ xlab("Percent of Land Used for Agriculture")+ ylab("Percent of Land Covered in Forest")+ scale_y_continuous(breaks=seq(0, 100, 10))+ scale_x_continuous(breaks=seq(0, 100, 10))+ theme_gray()+ theme(plot.title=element_text(hjust=0.5, size=11), axis.title=element_text(size=9))

```

In Plot #1, I graphed the percent of land used for agriculture against the percent of land covered in forest for the different countries. I colored the data points by year and changed the size of the data points based on the number of malaria cases (per 100,000 people). There is a negative correlation between percent of land used for agriculture versus covered in forest. Additionally, the data points turn from green to red from left to right. This indicates that over time, increased land is being converted for agricultural purposes. Based on background research, there appears to be a causative relationship between decreased forest cover and increased agricultural land: deforestation occurs in order to create space for agricultural production because as the global population increases, the demand for food has increased. However, the plot above simply shows a correlation between these variables.

```{R}
#Plot #2
amazon <- final_join %>% filter(country %in% c("Brazil","Columbia", "Peru", "Bolivia", "Venezuela", "Guyana", "Suriname"))

 ggplot(amazon, aes(x = country, y = malaria))+
  geom_bar(aes(fill=country), stat="summary",fun=mean)+
  geom_errorbar(stat="summary", fun.data=mean_se, width=.5)+ ggtitle("Average Malaria Incidence Rate in Amazonian Countries (1995-2005)")+ xlab("Country")+ ylab("Malaria Cases (per 100,000 people)")+ theme(legend.position="none")+ theme(plot.title=element_text(hjust=0.5), axis.text=element_text(size=10))+ scale_y_continuous(breaks=seq(0, 5000, 500))


```

In Plot #2, I created a bar graph depicting the average number of malaria cases (per 100,000 people) in countries that overlap with the Amazon Rainforest between the years 1995 and 2005. I chose to graph these countries because background research indicates that the Amazon is undergoing significant deforestation, and the wildlife-human interface (contact between humans, malaria-carrying mosquitoes, and animals that are food sources for mosquitoes) has changed as a result. Guyana had the most variation in malaria cases between the years, and Venezuela's malaria cases were fairly constant across the 11 years (as indicated by the lengths of the error bars). Additionally, countries that had higher rates of malaria incidence also tended to have longer error bars (i.e. there is more variation in the rate of malaria cases over time in countries that tend to have larger overall rates of malaria cases). 

```{R}
# Plot #3
deforest <- final_join %>% filter(country %in% c("Nigeria","Honduras", "Philippines", "Benin", "Ghana", "Indonesia", "Nepal"))

ggplot(data = deforest, aes(x= year, y= livestock))+ geom_point(aes(color=country), size=2)+ geom_smooth(aes(color=country), method="lm", se=F, size=.5)+ theme_gray()+ ggtitle("Livestock Production in Countries with High Deforestation Rates")+ ylab("Livestock Production Index")+ xlab("Year")+ scale_x_continuous(breaks=seq(1995, 2005, 1))+ geom_point(stat="summary", size=4)+ geom_smooth(method="lm", color="black")+ theme(plot.title=element_text(hjust=0.5))+ scale_color_discrete("Country")

```
According to previous research, global demand for animal products has increased, especially demand for meat, as countries across the globe become more developed. As a consequence, livestock production is increasing. Additionally, raising animals for meat uses a significant amount of land and is noted as one of the primary drivers of deforestation. In Plot #3, I graphed the Livestock Production Index of 7 countries that are known for having high rates of deforestation. (The Livestock Production Index was a measurement created to assess the amount of animal products produced in different countries, and the values range from 32.64 to 359.72). There is a positive correlation between time and the Livestock Production Index. In other words, as time passes (between 1995-2005), the magnitude of livestock production in countries with high deforestation rates increases. I also graphed the overall Livestock Production Index of these countries overtime (the black data points). Based on the plot, it appears that overall livestock production increased from approximately 58 to 88 from 1995 to 2005.

```{R}
#Plot #4
high_malaria <- final_join %>% filter(country %in% c("Zambia","Uganda", "Malawi", "Sao Tome and Principe", "Burundi"))

 ggplot(high_malaria, aes(x = country, y = agriculture))+
  geom_boxplot(aes(fill=country))+ ggtitle("Percent of Land Used for Agriculture in Countries with the Highest Malaria Incidence Rates from 1995-2005")+ xlab("Country")+ ylab("Percent of Land Used for Agriculture")+ theme_bw()+ theme(legend.position="none")+ theme(plot.title=element_text(hjust=0.5, size=10), axis.text=element_text(size=11))+ scale_y_continuous(breaks=seq(0,100,10))+ geom_jitter(alpha=.5, aes(color=country))


```
In Plot #4, I created a boxplot graph of the percent of land used for agriculture (averaged from 1995-2005) for the countries that had the highest number of malaria cases (per 100,000 people). The countries were chosen based on the results of Data Wrangling Demonstration #1 (above). There appears to be variation in the percent of land used for agriculture across the 5 countries. Zambia, which had the highest overall malaria incidence rate, had the lowest overall percent of land used for agriculture. Excluding Zambia, the countries had approximately between 45-75% of their land used for agriculture.

#### Concluding Remarks

Based on the analyses above, there appears to be a relationship between environmental factors and the incidence of malaria. (However, it is important to note that all of these analyses show correlations and therefore do not show causative relationships between the variables.) It was interesting to take patterns that are observed in the real world and apply data science techniques to them to see if my analyses also demonstrated these trends. Environmental factors have also been studied in the context of zoonotic emergence (Ebola, SARS-CoV-2, Nipah, etc.), so it could be interesting to analyze the relationship between the emergence of zoonoses and the presence of these environmental factors at their outbreak sites. 




